{
  "formatVersion": "1.1",
  "component": {
    "group": "com.b231001.bmaterial",
    "module": "ui-components-listitem",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-button",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-switch",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-listitem-1.3.1.aar",
          "url": "ui-components-listitem-1.3.1.aar",
          "size": 51032,
          "sha512": "dede637970dbb41ddcad6e59f78ab5ea2ec0c7c1ce17fe9518282f90b0d23c6fe9e0646ccafff9de3ec5e1e8801b23c4f37f99d28ae88b2471f6a578d26c762c",
          "sha256": "e79d2de23ffdf8436ebca985476c166aa3b6fd894df8e375fc185aacbc45a590",
          "sha1": "f51606d72af37204645a2c4953f56a0547a57da6",
          "md5": "e94e63e5c3e8493ce58fad79d831c16b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-button",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-switch",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-listitem-1.3.1.aar",
          "url": "ui-components-listitem-1.3.1.aar",
          "size": 51032,
          "sha512": "dede637970dbb41ddcad6e59f78ab5ea2ec0c7c1ce17fe9518282f90b0d23c6fe9e0646ccafff9de3ec5e1e8801b23c4f37f99d28ae88b2471f6a578d26c762c",
          "sha256": "e79d2de23ffdf8436ebca985476c166aa3b6fd894df8e375fc185aacbc45a590",
          "sha1": "f51606d72af37204645a2c4953f56a0547a57da6",
          "md5": "e94e63e5c3e8493ce58fad79d831c16b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-listitem-1.3.1-sources.jar",
          "url": "ui-components-listitem-1.3.1-sources.jar",
          "size": 4342,
          "sha512": "9b4b47ca6b9a375c713edf658f9dd7c212a4abed080974ebf22df50863c941495c4657112a07a2189f031acf35957e97d6600f8b4bd8b72592c80391c14608cb",
          "sha256": "5601f33dbebc4add40f9a221b2527d8ebdd5b72e0503a0896087f39c2118d362",
          "sha1": "12986d762d30d9ce7922138183c2a74a9cb9064a",
          "md5": "662b80efc7d1f23ad7a094578acbe968"
        }
      ]
    }
  ]
}
