{
  "formatVersion": "1.1",
  "component": {
    "group": "com.b231001.bmaterial",
    "module": "ui-components-snackbar",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-snackbar-1.3.1.aar",
          "url": "ui-components-snackbar-1.3.1.aar",
          "size": 42209,
          "sha512": "1384c093dfdda3b678b621b24d2405e9af9b6ce963017de1222cce7c5cac2a5700c499ecdbf16394c79fe5dc27a52ffa2c1d429c637f15ddf0a894f6f2730650",
          "sha256": "660da612e61f351dbdcc926f9bbf04c2e8051c98e6f27a7d8409823a4e37b124",
          "sha1": "6151ddc5c88b300a33afa04683f600fb987279c2",
          "md5": "232719becaaa8b34c39eca1a6114b633"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-snackbar-1.3.1.aar",
          "url": "ui-components-snackbar-1.3.1.aar",
          "size": 42209,
          "sha512": "1384c093dfdda3b678b621b24d2405e9af9b6ce963017de1222cce7c5cac2a5700c499ecdbf16394c79fe5dc27a52ffa2c1d429c637f15ddf0a894f6f2730650",
          "sha256": "660da612e61f351dbdcc926f9bbf04c2e8051c98e6f27a7d8409823a4e37b124",
          "sha1": "6151ddc5c88b300a33afa04683f600fb987279c2",
          "md5": "232719becaaa8b34c39eca1a6114b633"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-snackbar-1.3.1-sources.jar",
          "url": "ui-components-snackbar-1.3.1-sources.jar",
          "size": 3132,
          "sha512": "8d4d4e9ee838447052ad3983032ba90b427614ed74fe738488db4478eb5d400c7fcb697597fd087fb79bcd6ab26ebb5b6ade469bfd876e1212900589f3045d7c",
          "sha256": "a7db8c8dfde5a44ec210ad0b70c74c7cab7750490567f8e39f5f39c25b5b9cb3",
          "sha1": "51e2ee6d5f4270dc7c0552525389ed67c22bee15",
          "md5": "e0dba3b473e716f18a02b586f38f5d5b"
        }
      ]
    }
  ]
}
