{
  "formatVersion": "1.1",
  "component": {
    "group": "com.b231001.bmaterial",
    "module": "ui-components-chip",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-chip-1.3.1.aar",
          "url": "ui-components-chip-1.3.1.aar",
          "size": 38991,
          "sha512": "220e7a5f3a29cbe892a434dfe42ecfaa7b18e51d7b80284192f63ac8469115b1ecad68c04e5204faa4b33de3a270136761554267abbdc50fd1f17d4b1493ef1a",
          "sha256": "2ce2c14cd0cae6214ed9522be2397274deb808706c844f99cf13475429bb9fea",
          "sha1": "7f7ad3a77b52e1edc3507fc460011002c8815c94",
          "md5": "122857f49618299bd8dfa2c571dc846f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-chip-1.3.1.aar",
          "url": "ui-components-chip-1.3.1.aar",
          "size": 38991,
          "sha512": "220e7a5f3a29cbe892a434dfe42ecfaa7b18e51d7b80284192f63ac8469115b1ecad68c04e5204faa4b33de3a270136761554267abbdc50fd1f17d4b1493ef1a",
          "sha256": "2ce2c14cd0cae6214ed9522be2397274deb808706c844f99cf13475429bb9fea",
          "sha1": "7f7ad3a77b52e1edc3507fc460011002c8815c94",
          "md5": "122857f49618299bd8dfa2c571dc846f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-chip-1.3.1-sources.jar",
          "url": "ui-components-chip-1.3.1-sources.jar",
          "size": 3910,
          "sha512": "5d1dfb7c99921abee80d307cd758424bebd6393f124ac7fab0d56508d65b24ba81bc384a3f118f160b2cf118195d2ff896126df62f9707c68b75a1e6401d943b",
          "sha256": "e36247fea65ae5ceeb802834fd7721acf16d7472207c1bfb6bf6ce8179a329e4",
          "sha1": "0e561b130c5e7159b2bd917d4e373f306e103ce0",
          "md5": "8d0bfce9d6f20ae210a3984b961a22d6"
        }
      ]
    }
  ]
}
