{
  "formatVersion": "1.1",
  "component": {
    "group": "com.b231001.bmaterial",
    "module": "ui-components-dialog",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-dialog-1.3.1.aar",
          "url": "ui-components-dialog-1.3.1.aar",
          "size": 30453,
          "sha512": "469a1e9be0fddd175e77767ad159ab33bf2af741fa4c84d39e8f28d63416ae7eedafb35bca3b7a7680c5c87732a503dd40282cc90f11ea55dc58e09ec9654e72",
          "sha256": "b0b156b58e7df6afd8371170f0a5f53195075be34333385a77a113c8ef4ee0cb",
          "sha1": "f99f892728090488601ed0297d20bb20e22f6efb",
          "md5": "807b9eed13a125136620eee46455cf0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-dialog-1.3.1.aar",
          "url": "ui-components-dialog-1.3.1.aar",
          "size": 30453,
          "sha512": "469a1e9be0fddd175e77767ad159ab33bf2af741fa4c84d39e8f28d63416ae7eedafb35bca3b7a7680c5c87732a503dd40282cc90f11ea55dc58e09ec9654e72",
          "sha256": "b0b156b58e7df6afd8371170f0a5f53195075be34333385a77a113c8ef4ee0cb",
          "sha1": "f99f892728090488601ed0297d20bb20e22f6efb",
          "md5": "807b9eed13a125136620eee46455cf0b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-dialog-1.3.1-sources.jar",
          "url": "ui-components-dialog-1.3.1-sources.jar",
          "size": 2630,
          "sha512": "54be694e35a29f1e9b8fff64fbc76dd2ae8d7d1394e7cd83563de74d46198e8cfeeb4a72b611aef82470c1ac2da6a263f31f8d8f84faa4d72102b495c5ccf35a",
          "sha256": "13910880108e2f025249f1d10c9eb8a3b0d463faddc056cce414db7f37ed71d3",
          "sha1": "89fcfa084c463bbd99481149d5229b39a429fc50",
          "md5": "b7dbef6a6b49ef8dba43eb9e1b8b169f"
        }
      ]
    }
  ]
}
