{
  "formatVersion": "1.1",
  "component": {
    "group": "com.b231001.bmaterial",
    "module": "ui-components-layout",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-switch",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-button",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-layout-1.3.1.aar",
          "url": "ui-components-layout-1.3.1.aar",
          "size": 279931,
          "sha512": "955dfd6b710aa1b481f34d754868ebb8401727970613835747d32eba3bc6803f7767e299dc661e87f7add8f85d16187187149b0c10d135dae730168680bcf050",
          "sha256": "4f750190826a6b1e40ee6852c5aa0f5dff9856decb0a610346bc9c4b39e10f30",
          "sha1": "7aa951e797a1d9fb5392fb622950d10c96d01196",
          "md5": "e69e1204ad7a7dbfeeb394d75cae3fe4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2023.10.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-android"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-core-tokens",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-switch",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.b231001.bmaterial",
          "module": "ui-components-button",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-components-layout-1.3.1.aar",
          "url": "ui-components-layout-1.3.1.aar",
          "size": 279931,
          "sha512": "955dfd6b710aa1b481f34d754868ebb8401727970613835747d32eba3bc6803f7767e299dc661e87f7add8f85d16187187149b0c10d135dae730168680bcf050",
          "sha256": "4f750190826a6b1e40ee6852c5aa0f5dff9856decb0a610346bc9c4b39e10f30",
          "sha1": "7aa951e797a1d9fb5392fb622950d10c96d01196",
          "md5": "e69e1204ad7a7dbfeeb394d75cae3fe4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-layout-1.3.1-sources.jar",
          "url": "ui-components-layout-1.3.1-sources.jar",
          "size": 25882,
          "sha512": "631277b584299b50cfc3895dc6f26527822d565e326420e8875127b52b9a3042b2d9ef3950b251d9d38ad28fa73be4302b8ce6e66725f3df085b31f751da4671",
          "sha256": "79ef1c8600754508a3bbbee34d9673faabc32a5c582f17307b47f53c017a41a5",
          "sha1": "44e59e5ee4b9cb0072a4eef0d35b79e5cbb52dfb",
          "md5": "0091f840f96a95492c7eb9b6c4806860"
        }
      ]
    }
  ]
}
